---
- name: Extracting Ansible Facts
  hosts: webservers,balancers
  become: yes

  tasks:
    - name: Collecting hosts machine info
      ansible.builtin.copy:
        dest: /tmp/facts.txt
        content: |
          hostname: {{ ansible_hostname }}
          FQDN: {{ ansible_fqdn }}
          Distribution: {{ ansible_distribution }}
          IP Address: {{ ansible_default_ipv4.address }}
          BIOS Version: {{ ansible_bios_version }}


