---
- name: Ansible vault and secure variables
  hosts: all
  become: yes

  vars_files:
    - /home/automation/ansible1/secret.yml
      
  tasks:
    - name: Create user on all hosts
      ansible.builtin.user:
        name: scurry
        comment: "Stephen Curry"
        shell: /bin/bash
        group: goldenstate
        password: "{{ password | password_hash('sha512') }}" 

    - name: Display secret message
      ansible.builtin.debug:
        msg: "{{ secret_message }}"
