---
- name: Install and Enable Apache Webserver
  hosts: webservers
  become: true
  tasks:
    - name: Install the httpd package
      ansible.builtin.dnf:
        name: httpd
        state: latest

    - name: Start and enable the httpd service
      ansible.builtin.service:
        name: httpd
        state: latest

- name: Install and Enable Firewall
  hosts: webservers
  become: true
  tasks:          
    - name: Install the firewalld package
      ansible.builtin.dnf:
        name: httpd
        state: latest

    - name: Start and enable the firewalld service
      ansible.builtin.dnf:
        name: httpd
        state: latest
        enabled: true 

